
package fiches;

import donnees.Scores;

 
public class MeilleursScores extends javax.swing.JDialog {

    /**
     * Creates new form MeilleursScores
     */
    public MeilleursScores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("ARBRES ET TENTES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tp_scores = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_difficile = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_moyen = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_facile = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ta_difficile.setColumns(20);
        ta_difficile.setRows(5);
        jScrollPane1.setViewportView(ta_difficile);

        tp_scores.addTab("Difficile", jScrollPane1);

        ta_moyen.setColumns(20);
        ta_moyen.setRows(5);
        jScrollPane2.setViewportView(ta_moyen);

        tp_scores.addTab("Moyen", jScrollPane2);

        ta_facile.setColumns(20);
        ta_facile.setRows(5);
        jScrollPane3.setViewportView(ta_facile);

        tp_scores.addTab("Facile", jScrollPane3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("MEILLEURS SCORES");

        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(tp_scores, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_scores, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //bouton retour
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        getParent().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    //accesseurs aux text area :
    public javax.swing.JTextArea getTA_difficile() {
        return ta_difficile;
    }

    public javax.swing.JTextArea getTA_moyen() {
        return ta_moyen;
    }

    public javax.swing.JTextArea getTA_facile() {
        return ta_facile;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea ta_difficile;
    private javax.swing.JTextArea ta_facile;
    private javax.swing.JTextArea ta_moyen;
    private javax.swing.JTabbedPane tp_scores;
    // End of variables declaration//GEN-END:variables
}
